### ISSUE TITLE
Investigate the use of Kestrel instead of HttpListener

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/Polaris#12] opened 2017-10-10 21:51 UTC
[Kestrel](https://github.com/aspnet/KestrelHttpServer) is an awesome webserver from the ASP.NET folks. It might be worth using Kestrel instead of rolling our own webserver using HttpListener.

It has a lot of features that Polaris should have under the hood.

**Comment by chriskuech** [comment] 2017-11-26 19:11
Kestrel isn't part of .NET Standard, so Polaris would no longer work out-of-the-box on Windows.  Kestrel would make Polaris work as a high-performance web server; however, IMHO, the otherwise unfilled niche that Polaris perfectly fills is for DevOps engineers to quickly spin up web servers for telemetry, status pages, internal websites, etc.  Moving away from .NET Standard would move away from our heuristic of letting DevOps engineers (the primary PowerShell audience) quickly implement web servers.

**Comment by tylerl0706** [comment] 2017-11-26 22:20
@chriskuech what I've seen others do is include the dlls to libraries you depend on.

So we would include the dlls for Kestrel as a part of the release on the Gallery.

I don't really like the approach... But that seems to be the only decent option.

That said, we're pretty heavily invested in Httplistener so refactoring that will take some time.

I think I'm OK abandoning this idea (using Kestrel) and using ASP.NET routing in favor of the rewrite of Polaris in pure PowerShell. Then we can stick to Httplistener.

**Comment by tylerl0706** [comment] 2018-04-22 15:50
Is that in Windows PowerShell?

Looks like we can get that dll from:
https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/4.5.0-preview2-26406-04

**Comment by Tiberriver256** [comment] 2018-04-24 03:07
Got things quite a bit farther. I was copying a reference assembly instead of the lib into my lib folder.

https://gist.github.com/Tiberriver256/afb649f8543c86515adae3ce99ebbd6c

Now it's just a matter of the typical async problems of PowerShell. I'm getting back a Kestrel error that says there is no runspace available if I just feed it a scriptblock. I've been trying to figure out a good method to use the Task based asynchronous method in PowerShell and found the AsyncOps.ps1 on PowerShell gallery but I haven't had any such luck.

If anyone is handy enough with different async methods to tell me how to convert an asyncCallback to a Task we could continue with our current model of New-ScriptBlockCallback otherwise we've got to figure out a way to implement TAP in PowerShell...

**Comment by tylerl0706** [comment] 2018-04-24 15:07
Yeah for this, we'll need to hook up our Register-ObjectEvent. Just like we do with HttpListener, we'll need to have Kestrel trigger an event and then we use Register-ObjectEvent to handle it.

**Comment by tylerl0706** [comment] 2018-04-24 15:09
Speaking of async problems in PowerShell, @SeeminglyScience created an AWESOME PowerShell module for converting Script Blocks into delegates:
https://github.com/SeeminglyScience/PSLambda

It's amazing and I wonder if it'd be easy to adopt it to fix the "no runspace available" issue 🤔

**Comment by apetitjean** [comment] 2018-04-24 15:28
Speaking of async, are you aware of PoshRS module?
https://github.com/proxb/PoshRSJob


2018-04-24 17:09 GMT+02:00 Tyler James Leonhardt <notifications@github.com>:

**Comment by tylerl0706** [comment] 2018-04-24 16:11
Yeah! It's really nice. However, that just gives the ability to run a script block as a job. 

What we need is the ability to either - listen for events in PowerShell and then invoke a script block (aka Register-ObjectEvent) or convert our script block into a delegate so that we can pass that in to a .NET listener to get executed.

I support for Register-ObjectEvent we could run a PshRS job but I think that module spins up a runspace in the background and it may not be too performant.

**Comment by apetitjean** [comment] 2018-04-24 17:30
Okay, that makes sense.

2018-04-24 18:12 GMT+02:00 Tyler James Leonhardt <notifications@github.com>:

**Comment by Tiberriver256** [comment] 2018-04-24 20:02
@tylerl0706 - Agreed, if we can find anywhere that Kestrel supports the event based async model (beginxxxAsync and endxxxAsync) that would be ideal but right now I only see that it supports the task based asynchronous model ( xxxAsync ) which means we would have to look at something like lambdaPS but if you read into the code it's actually just wrapping runspaces so it may not solve our problem directly but definitely worth investigating.

**Comment by tylerl0706** [comment] 2018-04-25 00:40
@Tiberriver256 I looked over what you've done so far. It's looking good. Is this where the problem is:

https://gist.github.com/Tiberriver256/afb649f8543c86515adae3ce99ebbd6c#file-aplayingaroundwithkestrel-ps1-L39-L43

**Comment by SeeminglyScience** [comment] 2018-04-25 01:13
@Tiberriver256 

> which means we would have to look at something like lambdaPS but if you read into the code it's actually just wrapping runspaces so it may not solve our problem directly but definitely worth investigating.

Are you referring to PSLambda here?  Or the [AsyncOps]() class?

If you were referring to the latter, then yeah that one is just a wrapper that ends up sending the script block to a runspace pool.  Honestly I really recommend against using that, I wrote it before I learned all that much about PowerShell's event management.  A custom task wrapper that generates a `PSEvent` on a separate `runspace` would be *much* cleaner.  I can write up some more details if that route is chosen.

If you were referring to PSLambda though, that isn't the case.  The delegate created by PSLambda doesn't need a runspace and runs completely independently from the PowerShell engine.  But that's because the result isn't really PowerShell.  It looks a lot like it, has a lot of PowerShell-like comfort features, but it can't invoke commands and loses most of it's dynamic nature.  Using PSLambda for user supplied call backs would work, but the challenge in communicating those differences to the user should not be understated.

**Comment by Tiberriver256** [comment] 2018-04-25 02:49
Ah, thanks for jumping in here @SeeminglyScience! I've been trying to work with the AsyncOps class with not much luck.

A PSEvent on another runspace sounds super interesting, love to hear some more details on that!

**Comment by SeeminglyScience** [comment] 2018-04-25 03:28
Also, one of the reasons that code won't work is because PowerShell class methods are more or less just wrappers around script blocks.  If you try to invoke a PowerShell class method in a thread without a default runspace you'll get that same `InvalidOperationException`.  IIRC ASP.NET Core uses patterns like that a whole bunch, so might need some compiled wrapper classes.

**Comment by tylerl0706** [comment] 2018-04-26 23:46
> so might need some compiled wrapper classes

We're kinda already doing this now with the C# in:
https://github.com/PowerShell/Polaris/blob/master/Public/New-ScriptblockCallback.ps1

I would think that we could move a little bit of the Kestrel stuff into C#, handle what's async there and invoke an event from within that C#... kinda similar to my original example with HttpListener:
https://github.com/PowerShell/Polaris/issues/93#issuecomment-378662831

**Comment by Tiberriver256** [comment] 2018-04-27 00:57
Maybe like a Task to callback bridge? That would be nice.

**Comment by tylerl0706** [comment] 2018-04-27 02:56
Could use ContinueWith where the function inside ContinueWith triggers the event:

https://msdn.microsoft.com/en-us/library/dd270696(v=vs.110).aspx

**Comment by oising** [comment] 2018-04-27 20:03
See my back-of-a-napkin working example of a Task [to APM] to callback bridge over on https://github.com/PowerShell/PowerShell/issues/6716

**Comment by Tiberriver256** [comment] 2018-10-28 14:53
Were you ever able to find something on this?

**Comment by tylerl0706** [comment] 2018-11-01 17:06
I had a semi working example... but I had to wipe my computer and lost it. Will give it another go soon. I think I remember what's needed. Plus Kestrel is more mature now :smile:

**Comment by Tiberriver256** [comment] 2018-12-08 00:40
I think with Kestrel being based purely off of .Net tasks for async capabilities and PowerShell currently not supporting that very well I vote we should close this issue out for the foreseeable future and stick with HttpListener. It isn't going away. It just isn't getting any new features.

The main thing we will lose is the ability to to SSL in non-Windows environments within Polaris. For that I believe we should pick up the discussion in #107 and direct users towards using another tool like NGINX for SSL offloading.

**Comment by TylerLeonhardt** [comment] 2018-12-08 00:46
Perfectly reasonable!

**Closed** 2018-12-08 01:31 UTC
Labels: enhancement
