### ISSUE TITLE
An operation was attempted on a nonexistent network connection

### ISSUE THREAD

**Issue by TylerSiegrist** [PowerShell/Polaris#111] opened 2018-04-23 15:53 UTC
Seem to be getting this error somewhat regularly, typically during higher load. This occurs then Polaris stops responding completely until it is restarted. Can't find a ton on it but someone seems to have a similar issue [here](https://social.msdn.microsoft.com/Forums/en-US/5dd1f9bd-ca22-42ad-be2d-7336bb7c979d/httplistener-simultaneous-connections-give-httplistenerexception?forum=netfxnetcom). Not sure if it's worth digging into or just seeing if the move to Kestrel fixes the issue.

```
Exception calling "Write" with "3" argument(s): "An operation was attempted on a nonexistent network connection"
At C:\Scripts\UPH_Citrix_App\lib\Polaris.Class.ps1:237 char:9
+         $rawResponse.OutputStream.Write($byteResponse, 0, $byteRespon ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : HttpListenerException
```

**Comment by TylerSiegrist** [comment] 2018-04-24 00:24
Thanks for all your hard work on this project @tylerl0706 

```
Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Tiberriver256** [comment] 2018-04-24 01:51
The new implementation uses a CopyTo instead of a write which may make things better. I'd be interested to see.

Thanks for submitting these @TylerSiegrist. It's really handy.

**Comment by TylerSiegrist** [comment] 2018-04-24 01:57
I'll grab the latest version tomorrow morning and test it out, it looks like you're hard at work with all the recent commits!

I'll let you know how it goes, thanks!

**Comment by Tiberriver256** [comment] 2018-04-24 02:43
Cool yeah no problem. I was able to recreate the error pretty easily by just holding f5 in the browser which should actually produce that error message if the browser disconnects (i.e. tries again) before the server can send the file, and it was crashing the server!

So I put in some fixes :)

Also, knowing that is supposed to happen, if you're trying to simulate load from a browser. Here's a PowerShell script to simulate some heavy load from multiple clients. Just point it at the URL that serves a file and let her rip. It should all be 200 responses.

```ps
workflow PingUrlParallel {

  param(
    [string]$url,
    [int]$parallelCount = 10,
    [int]$iterations = 10
  )

  foreach -parallel ($x in 1..$parallelCount) {
    1..$iterations | %{ 
        $response = curl $url
        $status = $response.StatusCode
        "worker $x : iteration $_ : $status"
    }
  }
}

PingUrlParallel $MyURL -iterations 10
```
Script courtesy of @Buthrakaur: https://gist.github.com/Buthrakaur/376e0c05729ac6969e93

**Comment by tylerl0706** [comment] 2018-04-24 05:03
Just want to point something out. That example snippet uses `curl` which is no longer an alias anymore in PS Core.

**Comment by tylerl0706** [comment] 2018-05-19 01:45
I'm gonna close this since we can’t repo and have changed things. If you’re still seeing the problem, please open a new issue and we'll help further 😁

**Closed** 2018-05-19 01:46 UTC
Labels: bug

**Comment by bgelens** [comment] 2019-01-07 13:07
I'm getting this over and over again with latests release

![image](https://user-images.githubusercontent.com/10071039/50769842-81d9dd80-1285-11e9-9288-a24633dd831a.png)

**Comment by Tiberriver256** [comment] 2019-01-07 14:51
Hey @bgelens,

Looks like, although this is the same error message, possibly caused by a different chunk of code. Would you mind opening a new bug with (if possible) a link to the code you're running to generate the error?

Thank you!

**Comment by bgelens** [comment] 2019-01-07 15:08
Hi @Tiberriver256 

What happened is that the same route gets hit multiple times in a row.

This route only sets a Response StatusCode and some Header value so I did not use Send. Adding Send($null) resolved the issue.

I think the speed of the requests and not walking a path where Response gets disposed could cause this.

**Comment by Tiberriver256** [comment] 2019-01-07 15:22
Yep, definitely. Thanks for the response.
